### PR TITLE
Support for L5.1-dev

### PR DESCRIPTION
**Pull request by vluzrmos**

### CODE REVIEW

**Comment by franzliedke** [comment]
This package is not included in 5.1. Take a look at https://github.com/franzliedke/studio for an alternative. =)

**Comment by GrahamCampbell** [comment]
Please close this.

**Comment by vluzrmos** [comment]
Thanks, I will see that Studio.

**Comment by vluzrmos** [comment]
Amazing tool, thanks a lot @franzliedke !

**Pull request closed without merging**
